### ISSUE TITLE
CMake configure failing with ccmake

### ISSUE THREAD

**Issue by TeoKa** [robotology/codyco-superbuild#142] opened 2016-07-12 16:07 UTC
```
 CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FeatureSummary.cmake:304
 (CMAKE_PARSE_ARGUMENTS):
   Unknown CMake command "CMAKE_PARSE_ARGUMENTS".
 Call Stack (most recent call first):
   cmake/YCMBootstrap.cmake:76 (set_package_properties)
   CMakeLists.txt:84 (include)
```

**Comment by jeljaik** [comment] 2016-08-25 15:58
I have the exact same error today after updating `codyco-superbuild` on my OS X setup. Any hint guys? 

`cmake version 3.5.2`

**Comment by traversaro** [comment] 2016-08-25 16:52
Run : 
~~~
cmake .
~~~
without passing throught ccmake is a workaround for this issue.

**Comment by jeljaik** [comment] 2016-08-25 16:53
Yeah sure that's what I did. Still thought it would be cool to let you guys
know. A bit uncomfortable when you're looking for some specific options to
pass.

**Comment by traversaro** [comment] 2016-08-25 16:56
Ah, got it! Anyhow writing down the workaround may be useful for other people. For the issue itself we are unable to reproduce it on a simpler model at the moment.

**Comment by traversaro** [comment] 2016-09-09 07:55
We got the same problem on Windows :'''''( .
@MartaLorenzini can you paste the screenshot here?

**Comment by traversaro** [comment] 2016-09-09 07:57
In our case, restarting `cmake-gui` solved the problem.

**Comment by MartaLorenzini** [comment] 2016-09-09 09:14
2016-09-09 9:57 GMT+02:00 Silvio Traversaro <notifications@github.com>:

**Comment by jeljaik** [comment] 2016-09-20 11:44
Could it be related to what's mentioned [here](https://github.com/dmlc/mxnet/issues/1131) or [here](https://cmake.org/Bug/bug_relationship_graph.php?bug_id=14230&graph=dependency)?  a possibly missing `include(CMakeParseArguments)` in some YCM `cmake` file?

**Comment by traversaro** [comment] 2016-09-20 11:56
I don't think that is the case, as from CMake 3.5 `cmake_parse_arguments` is a built-in command and `CMakeParseArguments` is just an empty placeholder (see https://github.com/Kitware/CMake/blob/v3.5.0/Modules/CMakeParseArguments.cmake ).

**Comment by traversaro** [comment] 2018-04-18 22:04
I did not heard about anyone experiencing this problem in the last ~1.5 years, I will close this, please reopen (perhaps in https://github.com/robotology/robotology-superbuild) if necessary.

**Closed by traversaro** 2018-04-18 22:04 UTC
